name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master  # or main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PostCSS CLI and other dependencies
        run: |
          npm install -D postcss postcss-cli autoprefixer
          npm install -D @fullhuman/postcss-purgecss

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # Using latest version instead of 0.112.5
          extended: true    # Make sure to use extended version

      - name: Build
        run: hugo --minify

      - name: List files in public directory
        run: ls -R ./public
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
      
