name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master  # or 'main' depending on your default branch

permissions:
  contents: write  # This is important for deploying to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu is generally more reliable for CI/CD
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # If you're using git submodules for themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.112.5'
          extended: true    # If you need SCSS/SASS processing

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' # or 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages